Repository UIverse-Team/UIverse-BE, pull requests merged in 2025-03, with the labels that each got.

#37 [BE] 소셜로그인 회원가입 기능 및 세션 추가
  backend/JiShop/src/main/java/com/jishop/JiShopApplication.java
  backend/JiShop/src/main/java/com/jishop/controller/OAuthController.java
  backend/JiShop/src/main/java/com/jishop/controller/impl/GoogleControllerImpl.java
  backend/JiShop/src/main/java/com/jishop/controller/impl/KakaoControllerImpl.java
  backend/JiShop/src/main/java/com/jishop/controller/impl/NaverControllerImpl.java
  backend/JiShop/src/main/java/com/jishop/domain/User.java
  backend/JiShop/src/main/java/com/jishop/repository/UserRepository.java
  backend/JiShop/src/main/java/com/jishop/service/UserService.java
  backend/JiShop/src/main/java/com/jishop/service/impl/GoogleServiceImpl.java
  backend/JiShop/src/main/java/com/jishop/service/impl/UserServiceImpl.java
Labels: ✨ BE, 🚀 기능, 💻 개발

#39 [BE] feat: 검색 키워드 기반 공지사항 검색 기능 구현
  backend/JiShop/src/main/java/com/jishop/controller/NoticeController.java
  backend/JiShop/src/main/java/com/jishop/controller/impl/NoticeControllerImpl.java
  backend/JiShop/src/main/java/com/jishop/repository/NoticeRepository.java
  backend/JiShop/src/main/java/com/jishop/service/NoticeService.java
  backend/JiShop/src/main/java/com/jishop/service/impl/NoticeServiceImpl.java
Labels: ✨ BE, 🚀 기능, 📢 공지사항

#40 [BE] feat: 이메일 인증 구현
  backend/JiShop/build.gradle
  backend/JiShop/src/main/java/com/jishop/common/exception/ErrorType.java
  backend/JiShop/src/main/java/com/jishop/config/AwsSESConfig.java
  backend/JiShop/src/main/java/com/jishop/controller/EmailCertificationController.java
  backend/JiShop/src/main/java/com/jishop/controller/impl/AuthControllerImpl.java
  backend/JiShop/src/main/java/com/jishop/controller/impl/EmailCertificationControllerImpl.java
  backend/JiShop/src/main/java/com/jishop/domain/EmailCertification.java
  backend/JiShop/src/main/java/com/jishop/dto/EmailCertifyCodeRequest.java
  backend/JiShop/src/main/java/com/jishop/dto/EmailRequest.java
  backend/JiShop/src/main/java/com/jishop/repository/EmailCertificationRepository.java
  backend/JiShop/src/main/java/com/jishop/repository/UserRepository.java
  backend/JiShop/src/main/java/com/jishop/service/EmailCertificationService.java
  backend/JiShop/src/main/java/com/jishop/service/EmailSender.java
  backend/JiShop/src/main/java/com/jishop/service/impl/EmailCertificationServiceImpl.java
  backend/JiShop/src/main/java/com/jishop/service/impl/EmailSenderServiceImpl.java
Labels: ✨ BE

#48 [BE] refactor: 문자 인증 구현 코드 리펙토링
  backend/JiShop/src/main/java/com/jishop/common/exception/ErrorType.java
  backend/JiShop/src/main/java/com/jishop/controller/impl/SmsControllerImpl.java
  backend/JiShop/src/main/java/com/jishop/service/impl/SmsServiceImpl.java
Labels: ✨ BE, 🔒 인증 / 인가, ✅ 간단

#50 [BE] refactor: 인증/인가 파일 구조 통일 및 이름 수정
  backend/JiShop/src/main/java/com/jishop/common/exception/ErrorType.java
  backend/JiShop/src/main/java/com/jishop/controller/EmailCertificationController.java
  backend/JiShop/src/main/java/com/jishop/controller/SmsController.java
  backend/JiShop/src/main/java/com/jishop/controller/impl/AuthControllerImpl.java
  backend/JiShop/src/main/java/com/jishop/controller/impl/EmailCertificationControllerImpl.java
  backend/JiShop/src/main/java/com/jishop/controller/impl/SmsControllerImpl.java
  backend/JiShop/src/main/java/com/jishop/controller/impl/UserControllerImpl.java
  backend/JiShop/src/main/java/com/jishop/domain/SmsCertification.java
  backend/JiShop/src/main/java/com/jishop/dto/CertifyCodeRequest.java
  backend/JiShop/src/main/java/com/jishop/dto/EmailCertifyCodeRequest.java
  backend/JiShop/src/main/java/com/jishop/dto/SendVerificationRequest.java
  backend/JiShop/src/main/java/com/jishop/dto/SmsRequest.java
  backend/JiShop/src/main/java/com/jishop/repository/SmsCertificationRepository.java
  backend/JiShop/src/main/java/com/jishop/repository/SmsVerificationCodeRepository.java
  backend/JiShop/src/main/java/com/jishop/service/LoginService.java
  backend/JiShop/src/main/java/com/jishop/service/SmsCertificationService.java
  backend/JiShop/src/main/java/com/jishop/service/SmsService.java
  backend/JiShop/src/main/java/com/jishop/service/UserService.java
  backend/JiShop/src/main/java/com/jishop/service/impl/EmailCertificationServiceImpl.java
  backend/JiShop/src/main/java/com/jishop/service/impl/LoginServiceImpl.java
  backend/JiShop/src/main/java/com/jishop/service/impl/SmsCertificationServiceImpl.java
  backend/JiShop/src/main/java/com/jishop/service/impl/UserServiceImpl.java
Labels: ✨ BE, 🛠️ 리팩터링, ✅ 간단

#46 [BE] 외부서버 상품데이터 Polling 배치 처리(Springbatch) 적용
  backend/JiShop/build.gradle
  backend/JiShop/src/main/java/com/jishop/JiShopApplication.java
  backend/JiShop/src/main/java/com/jishop/batch/ProductDataBatchConfig.java
  backend/JiShop/src/main/java/com/jishop/batch/ProductDataJobRunner.java
  backend/JiShop/src/main/java/com/jishop/batch/ProductDataProcessor.java
  backend/JiShop/src/main/java/com/jishop/batch/ProductDataReader.java
  backend/JiShop/src/main/java/com/jishop/batch/ProductDataWriter.java
  backend/JiShop/src/main/java/com/jishop/domain/ProductData.java
  backend/JiShop/src/main/java/com/jishop/dto/productdata/ProductDataRequest.java
  backend/JiShop/src/main/java/com/jishop/scheduler/impl/ProductDataSchedulerImpl.java
  backend/JiShop/src/main/java/com/jishop/service/ProductDataService.java
  backend/JiShop/src/main/java/com/jishop/service/impl/ProductDataServiceImpl.java
  data/batchdb.mv.db
  data/batchdb.trace.db
Labels: ♻️ 테스트, 🎨 설계, 📦 상품

#55 [BE] feat: FAQ 전체 목록 조회 기능 구현
  backend/JiShop/src/main/java/com/jishop/faq/controller/FaqController.java
  backend/JiShop/src/main/java/com/jishop/faq/controller/FaqControllerImpl.java
  backend/JiShop/src/main/java/com/jishop/faq/domain/Faq.java
  backend/JiShop/src/main/java/com/jishop/faq/domain/FaqCategory.java
  backend/JiShop/src/main/java/com/jishop/faq/dto/FaqResponse.java
  backend/JiShop/src/main/java/com/jishop/faq/repository/FaqRepository.java
  backend/JiShop/src/main/java/com/jishop/faq/service/FaqService.java
  backend/JiShop/src/main/java/com/jishop/faq/service/FaqServiceImpl.java
  backend/JiShop/src/main/java/com/jishop/notice/controller/NoticeController.java
  backend/JiShop/src/main/java/com/jishop/notice/controller/NoticeControllerImpl.java
  backend/JiShop/src/main/java/com/jishop/notice/domain/Notice.java
  backend/JiShop/src/main/java/com/jishop/notice/domain/NoticePriority.java
  backend/JiShop/src/main/java/com/jishop/notice/dto/NoticeDetailResponse.java
  backend/JiShop/src/main/java/com/jishop/notice/dto/NoticeResponse.java
  backend/JiShop/src/main/java/com/jishop/notice/repository/NoticeRepository.java
  backend/JiShop/src/main/java/com/jishop/notice/service/NoticeService.java
  backend/JiShop/src/main/java/com/jishop/notice/service/NoticeServiceImpl.java
Labels: ✨ BE, 🧐 FAQ

#57 [BE] 주문 기능 구현
  backend/JiShop/src/main/java/com/jishop/common/exception/ErrorType.java
  backend/JiShop/src/main/java/com/jishop/common/exception/ExceptionController.java
  backend/JiShop/src/main/java/com/jishop/order/controller/OrderController.java
  backend/JiShop/src/main/java/com/jishop/order/controller/OrderControllerImpl.java
  backend/JiShop/src/main/java/com/jishop/order/domain/Order.java
  backend/JiShop/src/main/java/com/jishop/order/domain/OrderDetail.java
  backend/JiShop/src/main/java/com/jishop/order/domain/OrderNumber.java
  backend/JiShop/src/main/java/com/jishop/order/domain/OrderStatus.java
  backend/JiShop/src/main/java/com/jishop/order/dto/OrderDetailRequest.java
  backend/JiShop/src/main/java/com/jishop/order/dto/OrderDetailResponse.java
  backend/JiShop/src/main/java/com/jishop/order/dto/OrderRequest.java
  backend/JiShop/src/main/java/com/jishop/order/dto/OrderResponse.java
  backend/JiShop/src/main/java/com/jishop/order/repository/OrderNumberRepository.java
  backend/JiShop/src/main/java/com/jishop/order/repository/OrderRepository.java
  backend/JiShop/src/main/java/com/jishop/order/service/OrderNumberService.java
  backend/JiShop/src/main/java/com/jishop/order/service/OrderNumberServiceImpl.java
  backend/JiShop/src/main/java/com/jishop/order/service/OrderService.java
  backend/JiShop/src/main/java/com/jishop/order/service/OrderServiceImpl.java
Labels: ✨ BE, 🛒 주문

#69 [BE] 찜 상품 추가, 찜 물품 조회 구현
  backend/JiShop/src/main/java/com/jishop/batch/ProductDataBatchConfig.java
  backend/JiShop/src/main/java/com/jishop/batch/ProductDataJobRunner.java
  backend/JiShop/src/main/java/com/jishop/batch/ProductDataProcessor.java
  backend/JiShop/src/main/java/com/jishop/batch/ProductDataReader.java
  backend/JiShop/src/main/java/com/jishop/batch/ProductDataWriter.java
  backend/JiShop/src/main/java/com/jishop/config/WebConfig.java
  backend/JiShop/src/main/java/com/jishop/crawler/NaverStoreCrawler.java
  backend/JiShop/src/main/java/com/jishop/crawler/config/NaverCrawlerConfig.java
  backend/JiShop/src/main/java/com/jishop/crawler/dto/ProductCrawlerData.java
  backend/JiShop/src/main/java/com/jishop/domain/ProductData.java
  backend/JiShop/src/main/java/com/jishop/dto/productdata/ProductDataRequest.java
  backend/JiShop/src/main/java/com/jishop/member/controller/AuthControllerImpl.java
  backend/JiShop/src/main/java/com/jishop/product/domain/Product.java
  backend/JiShop/src/main/java/com/jishop/product/repository/ProductRepository.java
  backend/JiShop/src/main/java/com/jishop/saleproduct/repository/SaleProductRepository.java
  backend/JiShop/src/main/java/com/jishop/scheduler/ProductDataScheduler.java
  backend/JiShop/src/main/java/com/jishop/scheduler/impl/ProductDataSchedulerImpl.java
  backend/JiShop/src/main/java/com/jishop/wishlist/contoroller/WishListController.java
  backend/JiShop/src/main/java/com/jishop/wishlist/contoroller/WishListControllerImpl.java
  backend/JiShop/src/main/java/com/jishop/wishlist/domain/WishList.java
  backend/JiShop/src/main/java/com/jishop/wishlist/dto/WishProductRequest.java
  backend/JiShop/src/main/java/com/jishop/wishlist/dto/WishProductResponse.java
  backend/JiShop/src/main/java/com/jishop/wishlist/repository/WishListRepository.java
  backend/JiShop/src/main/java/com/jishop/wishlist/service/WishListService.java
  backend/JiShop/src/main/java/com/jishop/wishlist/service/WishListServiceImpl.java
Labels: ✨ BE

#71 [BE] 회원 id 찾기 구현
  backend/JiShop/src/main/java/com/jishop/member/controller/SignUpController.java
  backend/JiShop/src/main/java/com/jishop/member/controller/SignUpControllerImpl.java
  backend/JiShop/src/main/java/com/jishop/member/controller/UserController.java
  backend/JiShop/src/main/java/com/jishop/member/controller/UserControllerImpl.java
  backend/JiShop/src/main/java/com/jishop/member/dto/request/FindUserRequest.java
  backend/JiShop/src/main/java/com/jishop/member/dto/response/FindUserResponse.java
  backend/JiShop/src/main/java/com/jishop/member/repository/UserRepository.java
  backend/JiShop/src/main/java/com/jishop/member/service/UserService.java
  backend/JiShop/src/main/java/com/jishop/member/service/UserServiceImpl.java
Labels: ✨ BE

#75 ✨ feat: 아이디 찾기, 비밀번호 찾기
  backend/JiShop/src/main/java/com/jishop/common/exception/ErrorType.java
  backend/JiShop/src/main/java/com/jishop/member/controller/AuthController.java
  backend/JiShop/src/main/java/com/jishop/member/controller/EmailCertificationController.java
  backend/JiShop/src/main/java/com/jishop/member/controller/SignUpController.java
  backend/JiShop/src/main/java/com/jishop/member/controller/SmsController.java
  backend/JiShop/src/main/java/com/jishop/member/controller/UserController.java
  backend/JiShop/src/main/java/com/jishop/member/controller/UserControllerImpl.java
  backend/JiShop/src/main/java/com/jishop/member/controller/impl/AuthControllerImpl.java
  backend/JiShop/src/main/java/com/jishop/member/controller/impl/EmailCertificationControllerImpl.java
  backend/JiShop/src/main/java/com/jishop/member/controller/impl/GoogleControllerImpl.java
  backend/JiShop/src/main/java/com/jishop/member/controller/impl/KakaoControllerImpl.java
  backend/JiShop/src/main/java/com/jishop/member/controller/impl/NaverControllerImpl.java
  backend/JiShop/src/main/java/com/jishop/member/controller/impl/SignUpControllerImpl.java
  backend/JiShop/src/main/java/com/jishop/member/controller/impl/SmsControllerImpl.java
  backend/JiShop/src/main/java/com/jishop/member/controller/impl/UserControllerImpl.java
  backend/JiShop/src/main/java/com/jishop/member/domain/User.java
  backend/JiShop/src/main/java/com/jishop/member/dto/request/CertifyCodeRequest.java
  backend/JiShop/src/main/java/com/jishop/member/dto/request/EmailRequest.java
  backend/JiShop/src/main/java/com/jishop/member/dto/request/FinalStepRequest.java
  backend/JiShop/src/main/java/com/jishop/member/dto/request/RecoveryPWRequest.java
  backend/JiShop/src/main/java/com/jishop/member/dto/request/SignInFormRequest.java
  backend/JiShop/src/main/java/com/jishop/member/dto/request/SignUpFormRequest.java
  backend/JiShop/src/main/java/com/jishop/member/dto/request/SmsRequest.java
  backend/JiShop/src/main/java/com/jishop/member/dto/request/Step1Request.java
  backend/JiShop/src/main/java/com/jishop/member/dto/request/Step2Request.java
  backend/JiShop/src/main/java/com/jishop/member/dto/response/KakaoUserResponse.java
  backend/JiShop/src/main/java/com/jishop/member/dto/response/NaverUserResponse.java
  backend/JiShop/src/main/java/com/jishop/member/dto/response/SocialUserInfo.java
  backend/JiShop/src/main/java/com/jishop/member/dto/response/TokenResponse.java
  backend/JiShop/src/main/java/com/jishop/member/dto/response/UserIdResponse.java
  backend/JiShop/src/main/java/com/jishop/member/repository/UserRepository.java
  backend/JiShop/src/main/java/com/jishop/member/service/AbstractOAuthService.java
  backend/JiShop/src/main/java/com/jishop/member/service/EmailCertificationService.java
  backend/JiShop/src/main/java/com/jishop/member/service/OauthService.java
  backend/JiShop/src/main/java/com/jishop/member/service/SmsCertificationService.java
  backend/JiShop/src/main/java/com/jishop/member/service/UserService.java
  backend/JiShop/src/main/java/com/jishop/member/service/impl/EmailCertificationServiceImpl.java
  backend/JiShop/src/main/java/com/jishop/member/service/impl/EmailSenderServiceImpl.java
  backend/JiShop/src/main/java/com/jishop/member/service/impl/GoogleServiceImpl.java
  backend/JiShop/src/main/java/com/jishop/member/service/impl/KakaoServiceImpl.java
  backend/JiShop/src/main/java/com/jishop/member/service/impl/NaverServiceImpl.java
  backend/JiShop/src/main/java/com/jishop/member/service/impl/SmsCertificationServiceImpl.java
  backend/JiShop/src/main/java/com/jishop/member/service/impl/UserServiceImpl.java
Labels: ✨ BE

#78 [BE] 마이페이지 구현
  backend/JiShop/src/main/java/com/jishop/member/controller/AuthController.java
  backend/JiShop/src/main/java/com/jishop/member/controller/UserController.java
  backend/JiShop/src/main/java/com/jishop/member/controller/impl/AuthControllerImpl.java
  backend/JiShop/src/main/java/com/jishop/member/controller/impl/UserControllerImpl.java
  backend/JiShop/src/main/java/com/jishop/member/domain/User.java
  backend/JiShop/src/main/java/com/jishop/member/dto/request/UserNameRequest.java
  backend/JiShop/src/main/java/com/jishop/member/dto/request/UserPhoneRequest.java
  backend/JiShop/src/main/java/com/jishop/member/dto/response/UserResponse.java
  backend/JiShop/src/main/java/com/jishop/member/service/AuthService.java
  backend/JiShop/src/main/java/com/jishop/member/service/UserService.java
  backend/JiShop/src/main/java/com/jishop/member/service/impl/AuthServiceImpl.java
  backend/JiShop/src/main/java/com/jishop/member/service/impl/UserServiceImpl.java
Labels: ✨ BE, 🔒 인증 / 인가

#80 [BE} 상품 단건 조회 및 상품,스토어,카테고리 데이터(dump 파일) 최신화
  backend/JiShop/src/main/java/com/jishop/category/domain/Category.java
  backend/JiShop/src/main/java/com/jishop/order/controller/OrderController.java
  backend/JiShop/src/main/java/com/jishop/order/controller/OrderControllerImpl.java
  backend/JiShop/src/main/java/com/jishop/order/domain/OrderStatus.java
  backend/JiShop/src/main/java/com/jishop/order/dto/OrderRequest.java
  backend/JiShop/src/main/java/com/jishop/order/service/OrderService.java
  backend/JiShop/src/main/java/com/jishop/product/controller/ProductController.java
  backend/JiShop/src/main/java/com/jishop/product/controller/ProductControllerImpl.java
  backend/JiShop/src/main/java/com/jishop/product/domain/DiscountStatus.java
  backend/JiShop/src/main/java/com/jishop/product/domain/Product.java
  backend/JiShop/src/main/java/com/jishop/product/dto/ProductRequest.java
  backend/JiShop/src/main/java/com/jishop/product/dto/ProductResponse.java
  backend/JiShop/src/main/java/com/jishop/product/repository/ProductRepository.java
  backend/JiShop/src/main/java/com/jishop/product/service/ProductService.java
  backend/JiShop/src/main/java/com/jishop/product/service/ProductServiceImpl.java
  backend/JiShop/src/main/java/com/jishop/store/domain/Store.java
  backend/JiShop/src/main/resources/category_backup.sql
  backend/JiShop/src/main/resources/product_backup.sql
  backend/JiShop/src/main/resources/static/sqlbackup/category_backup0314.sql
  backend/JiShop/src/main/resources/static/sqlbackup/product_backup.sql
  backend/JiShop/src/main/resources/static/sqlbackup/product_backup0314.sql
  backend/JiShop/src/main/resources/static/sqlbackup/store_backup.sql
  backend/JiShop/src/main/resources/static/sqlbackup/store_backup0314.sql
  backend/JiShop/src/main/resources/store_backup.sql
Labels: 📦 상품

#93 [BE] 해당 회원 판별하기
  backend/JiShop/src/main/java/com/jishop/config/WebConfig.java
  backend/JiShop/src/main/java/com/jishop/member/annotation/CurrentUser.java
  backend/JiShop/src/main/java/com/jishop/member/annotation/CurrentUserResolver.java
  backend/JiShop/src/main/java/com/jishop/wishlist/contoroller/WishListController.java
  backend/JiShop/src/main/java/com/jishop/wishlist/contoroller/WishListControllerImpl.java
  backend/JiShop/src/main/java/com/jishop/wishlist/domain/WishList.java
  backend/JiShop/src/main/java/com/jishop/wishlist/repository/WishListRepository.java
  backend/JiShop/src/main/java/com/jishop/wishlist/service/WishListService.java
  backend/JiShop/src/main/java/com/jishop/wishlist/service/WishListServiceImpl.java
Labels: ✨ BE, 💻 개발, 🔒 인증 / 인가

#96 [BE] 주소 추가 및 주소 조회
  backend/JiShop/src/main/java/com/jishop/address/controller/AddressController.java
  backend/JiShop/src/main/java/com/jishop/address/controller/AddressControllerImpl.java
  backend/JiShop/src/main/java/com/jishop/address/domain/Address.java
  backend/JiShop/src/main/java/com/jishop/address/dto/AddressRequest.java
  backend/JiShop/src/main/java/com/jishop/address/dto/AddressResponse.java
  backend/JiShop/src/main/java/com/jishop/address/repository/AddressRepository.java
  backend/JiShop/src/main/java/com/jishop/address/service/AddressService.java
  backend/JiShop/src/main/java/com/jishop/address/service/AddressServiceImpl.java
  backend/JiShop/src/main/java/com/jishop/common/exception/ErrorType.java
  backend/JiShop/src/main/java/com/jishop/member/dto/request/EmailRequest.java
  backend/JiShop/src/main/java/com/jishop/member/dto/request/FinalStepRequest.java
  backend/JiShop/src/main/java/com/jishop/member/dto/request/RecoveryPWRequest.java
  backend/JiShop/src/main/java/com/jishop/member/dto/request/SmsRequest.java
  backend/JiShop/src/main/java/com/jishop/member/dto/request/Step1Request.java
  backend/JiShop/src/main/java/com/jishop/member/dto/request/Step2Request.java
  backend/JiShop/src/main/java/com/jishop/wishlist/contoroller/WishListController.java
  backend/JiShop/src/main/java/com/jishop/wishlist/contoroller/WishListControllerImpl.java
Labels: ✨ BE, 🤦🏿‍♂️회원

#128 [BE] 상품 카테고리 기능 구현
  backend/JiShop/src/main/java/com/jishop/category/controller/CategoryController.java
  backend/JiShop/src/main/java/com/jishop/category/controller/CategoryControllerImpl.java
  backend/JiShop/src/main/java/com/jishop/category/domain/Category.java
  backend/JiShop/src/main/java/com/jishop/category/dto/CategoryResponse.java
  backend/JiShop/src/main/java/com/jishop/category/repository/CategoryRepository.java
  backend/JiShop/src/main/java/com/jishop/category/service/CategoryService.java
  backend/JiShop/src/main/java/com/jishop/common/exception/ErrorType.java
  backend/JiShop/src/main/java/com/jishop/product/domain/Product.java
  backend/JiShop/src/main/java/com/jishop/product/dto/ProductListResponse.java
  backend/JiShop/src/main/java/com/jishop/product/dto/ProductRequest.java
  backend/JiShop/src/main/java/com/jishop/product/dto/ProductResponse.java
  backend/JiShop/src/main/java/com/jishop/product/implementation/ProductQueryHelperImpl.java
  backend/JiShop/src/main/java/com/jishop/product/repository/ProductRepository.java
  backend/JiShop/src/main/java/com/jishop/product/service/ProductServiceImpl.java
  backend/JiShop/src/main/java/com/jishop/saleproduct/repository/SaleProductRepository.java
Labels: 📦 상품

#137 [BE] 카테고리 필터링 기능 추가 및 인기 상품 10개 조회 기능 추가
  backend/JiShop/src/main/java/com/jishop/JiShopApplication.java
  backend/JiShop/src/main/java/com/jishop/category/dto/CategoryResponse.java
  backend/JiShop/src/main/java/com/jishop/category/repository/CategoryRepository.java
  backend/JiShop/src/main/java/com/jishop/product/controller/ProductController.java
  backend/JiShop/src/main/java/com/jishop/product/controller/ProductControllerImpl.java
  backend/JiShop/src/main/java/com/jishop/product/domain/SaleStatus.java
  backend/JiShop/src/main/java/com/jishop/product/dto/request/ProductRequest.java
  backend/JiShop/src/main/java/com/jishop/product/dto/response/ProductListResponse.java
  backend/JiShop/src/main/java/com/jishop/product/dto/response/ProductResponse.java
  backend/JiShop/src/main/java/com/jishop/product/implementation/ProductQueryHelper.java
  backend/JiShop/src/main/java/com/jishop/product/implementation/ProductQueryHelperImpl.java
  backend/JiShop/src/main/java/com/jishop/product/repository/ProductRepository.java
  backend/JiShop/src/main/java/com/jishop/product/repository/ProductRepositoryQueryDsl.java
  backend/JiShop/src/main/java/com/jishop/product/repository/ProductRepositoryQueryDslImpl.java
  backend/JiShop/src/main/java/com/jishop/product/service/ProductService.java
  backend/JiShop/src/main/java/com/jishop/product/service/ProductServiceImpl.java
  backend/JiShop/src/main/java/com/jishop/productwishlist/repository/ProductWishListRepository.java
  backend/JiShop/src/main/java/com/jishop/reviewproduct/domain/ReviewProduct.java
  backend/JiShop/src/main/resources/category_backup.sql
  backend/JiShop/src/main/resources/product_backup.sql
  backend/JiShop/src/main/resources/store_backup.sql
Labels: 📦 상품, 👍 상품 추천

#179 [BE] feat: 상품 점수화 시스템을 통한 인기 검색어와 인기 상품리스트 조회 기능 구현
  backend/JiShop/src/main/java/com/jishop/order/repository/OrderDetailRepository.java
  backend/JiShop/src/main/java/com/jishop/popular/controller/PopularController.java
  backend/JiShop/src/main/java/com/jishop/popular/controller/PopularControllerImpl.java
  backend/JiShop/src/main/java/com/jishop/popular/controller/SearchController.java
  backend/JiShop/src/main/java/com/jishop/popular/controller/SearchControllerImpl.java
  backend/JiShop/src/main/java/com/jishop/popular/dto/PopularKeywordResponse.java
  backend/JiShop/src/main/java/com/jishop/popular/dto/PopularProductResponse.java
  backend/JiShop/src/main/java/com/jishop/popular/dto/PopularReponse.java
  backend/JiShop/src/main/java/com/jishop/popular/service/PopularService.java
  backend/JiShop/src/main/java/com/jishop/popular/service/PopularServiceImpl.java
  backend/JiShop/src/main/java/com/jishop/popular/service/SearchServiceImpl.java
  backend/JiShop/src/main/java/com/jishop/product/repository/ProductRepository.java
  backend/JiShop/src/main/java/com/jishop/productscore/service/ProductScoreService.java
  backend/JiShop/src/main/java/com/jishop/productscore/service/ProductScoreServiceImpl.java
  backend/JiShop/src/main/java/com/jishop/reviewproduct/repository/ReviewProductRepository.java
Labels: ✨ BE, 💻 개발, 💪 아자아자!!, 📊 인기검색어

#196 [BE] feat: 문의사항 작성 및 조회 기능 구현
  backend/JiShop/src/main/java/com/jishop/common/exception/ErrorType.java
  backend/JiShop/src/main/java/com/jishop/order/repository/OrderRepository.java
  backend/JiShop/src/main/java/com/jishop/question/controller/QuestionController.java
  backend/JiShop/src/main/java/com/jishop/question/controller/QuestionControllerImpl.java
  backend/JiShop/src/main/java/com/jishop/question/domain/AnswerStatus.java
  backend/JiShop/src/main/java/com/jishop/question/domain/Question.java
  backend/JiShop/src/main/java/com/jishop/question/domain/QuestionCategory.java
  backend/JiShop/src/main/java/com/jishop/question/dto/QuestionRequest.java
  backend/JiShop/src/main/java/com/jishop/question/dto/QuestionResponse.java
  backend/JiShop/src/main/java/com/jishop/question/repository/QuestionCategoryRepository.java
  backend/JiShop/src/main/java/com/jishop/question/repository/QuestionRepository.java
  backend/JiShop/src/main/java/com/jishop/question/service/QuestionService.java
  backend/JiShop/src/main/java/com/jishop/question/service/QuestionServiceImpl.java
Labels: ✨ BE, 💻 개발, 🌿 문의사항

#209 [BE] feat: 인기 검색어 및 인기 상품 조회 기능 리팩토링
  backend/JiShop/src/main/java/com/jishop/config/RedisConfig.java
  backend/JiShop/src/main/java/com/jishop/popular/controller/PopularController.java
  backend/JiShop/src/main/java/com/jishop/popular/controller/PopularControllerImpl.java
  backend/JiShop/src/main/java/com/jishop/popular/controller/SearchController.java
  backend/JiShop/src/main/java/com/jishop/popular/scheduler/PopularProductScoreScheduler.java
  backend/JiShop/src/main/java/com/jishop/popular/service/PopularCalculationService.java
  backend/JiShop/src/main/java/com/jishop/popular/service/PopularCalculationServiceImpl.java
  backend/JiShop/src/main/java/com/jishop/popular/service/PopularService.java
  backend/JiShop/src/main/java/com/jishop/popular/service/PopularServiceImpl.java
  backend/JiShop/src/main/java/com/jishop/popular/service/SearchServiceImpl.java
  backend/JiShop/src/main/java/com/jishop/product/repository/ProductRepository.java
  backend/JiShop/src/main/java/com/jishop/productscore/repository/ProductScoreRepository.java
  backend/JiShop/src/main/java/com/jishop/productscore/service/ProductScoreServiceImpl.java
Labels: ✨ BE, 🛠️ 리팩터링, 📊 인기검색어

#223 [BE] 오늘의 특가 기능 추가
  backend/JiShop/src/main/java/com/jishop/category/controller/CategoryControllerImpl.java
  backend/JiShop/src/main/java/com/jishop/category/service/CategoryCacheService.java
  backend/JiShop/src/main/java/com/jishop/category/service/CategoryCacheServiceImpl.java
  backend/JiShop/src/main/java/com/jishop/category/service/CategoryRedisService.java
  backend/JiShop/src/main/java/com/jishop/category/service/CategoryRedisServiceImpl.java
  backend/JiShop/src/main/java/com/jishop/category/service/CategoryServiceImpl.java
  backend/JiShop/src/main/java/com/jishop/product/controller/ProductController.java
  backend/JiShop/src/main/java/com/jishop/product/controller/ProductControllerImpl.java
  backend/JiShop/src/main/java/com/jishop/product/dto/response/ProductListResponse.java
  backend/JiShop/src/main/java/com/jishop/product/dto/response/TodaySpecialListResponse.java
  backend/JiShop/src/main/java/com/jishop/product/repository/ProductRepository.java
  backend/JiShop/src/main/java/com/jishop/product/service/DiscountSatusScheduler.java
  backend/JiShop/src/main/java/com/jishop/product/service/ProductService.java
  backend/JiShop/src/main/java/com/jishop/product/service/ProductServiceImpl.java
Labels: 📦 상품

#238 [BE] feat: 현재 급상승 키워드(인기 검색어/인기 상품) 디테일 페이지 구현
  backend/JiShop/build.gradle
  backend/JiShop/src/main/java/com/jishop/popular/controller/PopularController.java
  backend/JiShop/src/main/java/com/jishop/popular/controller/PopularControllerImpl.java
  backend/JiShop/src/main/java/com/jishop/popular/scheduler/PopularProductScoreScheduler.java
  backend/JiShop/src/main/java/com/jishop/popular/service/PopularCalculationServiceImpl.java
  backend/JiShop/src/main/java/com/jishop/popular/service/PopularService.java
  backend/JiShop/src/main/java/com/jishop/popular/service/PopularServiceImpl.java
  backend/JiShop/src/main/java/com/jishop/popular/service/SearchServiceImpl.java
  backend/JiShop/src/main/resources/logback-spring.xml
Labels: ✨ BE, 📊 인기검색어

#249 [BE] feat: Swagger 수정 및 공지사항 검색 쿼리 수정
  backend/JiShop/src/main/java/com/jishop/faq/controller/FaqController.java
  backend/JiShop/src/main/java/com/jishop/notice/controller/NoticeController.java
  backend/JiShop/src/main/java/com/jishop/notice/repository/NoticeRepository.java
Labels: ✨ BE, 🛠️ 리팩터링, 📢 공지사항

#257 [BE] 상품 목록 조회 응답 구조 수정 및 카테고리 리펙토링
  backend/JiShop/src/main/java/com/jishop/category/controller/CategoryController.java
  backend/JiShop/src/main/java/com/jishop/category/controller/CategoryControllerImpl.java
  backend/JiShop/src/main/java/com/jishop/category/dto/CategoryDropDownResponse.java
  backend/JiShop/src/main/java/com/jishop/category/dto/CategoryResponse.java
  backend/JiShop/src/main/java/com/jishop/category/dto/SubCategory.java
  backend/JiShop/src/main/java/com/jishop/category/repository/CategoryRepository.java
  backend/JiShop/src/main/java/com/jishop/category/service/CategoryInfoService.java
  backend/JiShop/src/main/java/com/jishop/category/service/CategoryRedisService.java
  backend/JiShop/src/main/java/com/jishop/category/service/CategoryRedisServiceImpl.java
  backend/JiShop/src/main/java/com/jishop/category/service/CategoryService.java
  backend/JiShop/src/main/java/com/jishop/category/service/CategoryServiceImpl.java
  backend/JiShop/src/main/java/com/jishop/category/service/Impl/CategoryRedisServiceImpl.java
  backend/JiShop/src/main/java/com/jishop/category/service/Impl/CategoryServiceImpl.java
  backend/JiShop/src/main/java/com/jishop/product/controller/ProductController.java
  backend/JiShop/src/main/java/com/jishop/product/controller/ProductControllerImpl.java
  backend/JiShop/src/main/java/com/jishop/product/dto/request/ProductRequest.java
  backend/JiShop/src/main/java/com/jishop/product/dto/response/ProductDetailResponse.java
  backend/JiShop/src/main/java/com/jishop/product/dto/response/ProductListResponse.java
  backend/JiShop/src/main/java/com/jishop/product/dto/response/ProductResponse.java
  backend/JiShop/src/main/java/com/jishop/product/dto/response/TodaySpecialListResponse.java
  backend/JiShop/src/main/java/com/jishop/product/implementation/ProductQueryHelperImpl.java
  backend/JiShop/src/main/java/com/jishop/product/service/ProductService.java
  backend/JiShop/src/main/java/com/jishop/product/service/ProductServiceImpl.java
  backend/JiShop/src/main/java/com/jishop/productwishlist/repository/ProductWishListRepository.java
Labels: 🗂️ 카테고리

#254 [BE] feat: 인기 상품 리스트 반환 로직 수정
  backend/JiShop/src/main/java/com/jishop/popular/scheduler/PopularProductScoreScheduler.java
  backend/JiShop/src/main/java/com/jishop/popular/service/PopularCalculationServiceImpl.java
  backend/JiShop/src/main/java/com/jishop/popular/service/PopularServiceImpl.java
  backend/JiShop/src/main/java/com/jishop/popular/service/SearchServiceImpl.java
Labels: ✨ BE, 📊 인기검색어

#261 [BE] docs: 문의사항 API에 Swagger 추가
  backend/JiShop/src/main/java/com/jishop/question/controller/QuestionController.java
Labels: 📋 문서
